name: SonarQube Scan

on:
  push:
    branches:
      - master

jobs:
  sonar:
    runs-on: debian-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://kab.naktech.pro:9000
